create table users (
                       id         bigint generated by default as identity primary key,
                       name       varchar(255) not null,
                       email      varchar(255) not null unique,
                       created_at timestamp(6) with time zone not null
);

create table categories (
                            id   bigint generated by default as identity primary key,
                            name varchar(255) not null unique
);

create table items (
                       id          bigint generated by default as identity primary key,
                       title       varchar(255) not null,
                       description text,
                       price       numeric(12, 2),
                       city        varchar(255) not null,
                       status      varchar(20)  not null,
                       owner_id    bigint       not null,
                       category_id bigint       not null,
                       created_at  timestamp(6) with time zone not null,
                       constraint fk_items_owner    foreign key (owner_id)    references users (id),
                       constraint fk_items_category foreign key (category_id) references categories (id)
);