create table subscriptions (
                               id          bigint generated by default as identity primary key,
                               user_id     bigint not null,
                               category_id bigint not null,
                               city        varchar(255),
                               created_at  timestamp(6) with time zone not null,
                               constraint fk_subscriptions_user     foreign key (user_id)     references users (id) on delete cascade,
                               constraint fk_subscriptions_category foreign key (category_id) references categories (id) on delete cascade,
                               constraint uq_subscriptions_user_category_city unique (user_id, category_id, city)
);

create table notifications (
                               id         bigint generated by default as identity primary key,
                               user_id    bigint not null,
                               item_id    bigint not null,
                               message    text   not null,
                               is_read    boolean not null default false,
                               created_at timestamp(6) with time zone not null,
                               constraint fk_notifications_user foreign key (user_id) references users (id) on delete cascade,
                               constraint fk_notifications_item foreign key (item_id) references items (id) on delete cascade
);

create index idx_subscriptions_category on subscriptions (category_id);
create index idx_notifications_user      on notifications (user_id);