create table outbox (
                        id             bigint generated by default as identity primary key,
                        aggregate_type varchar(100) not null,
                        aggregate_id   varchar(100) not null,
                        event_type     varchar(100) not null,
                        payload        text         not null,
                        published      boolean      not null default false,
                        created_at     timestamp(6) with time zone not null,
                        published_at   timestamp(6) with time zone
);

create index idx_outbox_unpublished on outbox (created_at) where published = false;